### ISSUE TITLE
Not.to_string() conversion has unneeded double-parenthesis if the inner expression is a binary operator

### ISSUE THREAD

**Issue by jenisys** [cucumber/tag-expressions#94]
### 👓 What did you see?

If a tag-expression contains a `not` operator that encapsulate a binary operator (`and`, `or`),
the string conversion currently leads to double-parenthesis (unnecessary tautology).
This makes the textual string less readable and understandable.

EXAMPLE:

```yaml
# SOURCE: testdata/parsing.yml
# HINT: This data or similar examples are currently missing

- expression: 'not (a and b)'
  formatted.currently: 'not ( ( a and b ) )'
  formatted.should_be: 'not ( a and b )'
```

REASONS:

* The binary operators put already parenthesis around their boolean expression during string conversion
* If the `not` operator does the same (as it currently is implemented), we get two groups of parenthensis

AFFECTED:

* ALL tag-expression implementations

### ✅ What did you expect to see?

Only one parenthesis grouping, like the `formatted.should_be` case shown in the example above.

### 📦 Which tool/library version are you using?

I added additional case to the `testdata/parsing.yml` in my local workspace and run Java, Javascript and Go implementations.
Each failed the new additional tests.
The non-tested implementations (Ruby and Perl) are also be affected (as expected), by inspection of their implementation.

### 🔬 How could we reproduce it?

Add the following test-data items to `testdata/parsing.yml`:

```yaml
# SOURCE: testdata/parsing.yml

# BAD_EXAMPLES (how the string output currently is):

- expression: 'not (a and b)'
  formatted: 'not ( ( a and b ) )'
- expression: 'not (a or b)'
  formatted: 'not ( ( a or b ) )'
- expression: 'not (a and b) and c or not (d or f)'
  formatted: '( ( not ( ( a and b ) ) and c ) or not ( ( d or f ) ) )'

# GOOD_EXAMPLES (how the output should be):

- expression: 'not (a and b)'
  formatted: 'not ( a and b )'
- expression: 'not (a or b)'
  formatted: 'not ( a or b )'
- expression: 'not (a and b) and c or not (d or f)'
  formatted: '( ( not ( a and b ) and c ) or not ( d or f ) )'
```

0. Update the local workspace to the current HEAD of the GitHub:/cucumber/tag-expression repository.
1. Patch the testdata file
2. Run the tests for each implementation

### 📚 Any additional context?

Nope.
